In [4]:
import pandas as pd

In [5]:
df = pd.read_json("bank_accounts.json")

In [7]:
df

,Account name,Account number,Amount,Type,Status,Current Balance,Date
0,Aman,2980839364788295,5000,Deposit,Success,5000,2026-10-22
1,Aman,2980839364788295,9000,Deposit,Success,14000,2026-10-22
2,Sandeep Kumar,2819547530229529,45000,Deposit,Success,45000,2026-10-22
3,Sandeep Kumar,2819547530229529,25000,Withdraw,Success,20000,2026-10-22
4,Sandeep,2875528873295950,60000,Deposit,Success,60000,2026-10-22
5,Sumit,6227492284319474,50000,Deposit,Success,50000,2026-10-22
6,Sandeep,2875528873295950,9000,Withdraw,Success,51000,2026-10-22
7,Sumit,6227492284319474,6000,Withdraw,Success,44000,2026-10-22
8,Sumit,6227492284319474,4500,Withdraw,Success,39500,2026-10-22
9,Sandeep,2875528873295950,4600,Withdraw,Success,46400,2026-10-22
10,Sumit,6227492284319474,5000,Withdraw,Success,34500,2026-10-23
11,Sumit,6227492284319474,20000,Deposit,Success,54500,2026-10-23
12,Sandeep,2875528873295950,12300,Withdraw,Success,34100,2026-10-23
13,Sandeep,2875528873295950,14000,Withdraw,Success,20100,2026-10-23
14,Sumit,6227492284319474,3200,Withdraw,Success,51300,2026-10-23
15,Sandeep,2875528873295950,6400,Withdraw,Success,13700,2026-10-23

In [34]:
df.head()

,Account name,Account number,Amount,Type,Status,Current Balance,Date
0,Aman,2980839364788295,5000,Deposit,Success,5000,2026-10-22
1,Aman,2980839364788295,9000,Deposit,Success,14000,2026-10-22
2,Sandeep Kumar,2819547530229529,45000,Deposit,Success,45000,2026-10-22
3,Sandeep Kumar,2819547530229529,25000,Withdraw,Success,20000,2026-10-22
4,Sandeep,2875528873295950,60000,Deposit,Success,60000,2026-10-22

In [8]:
df2 = df.copy()

In [15]:
#Which transaction types occur most frequently?
df2["Type"].value_counts()

Type
Withdraw    10
Deposit      6
Name: count, dtype: int64

In [21]:
#What is the highest transaction amount?
df2["Amount"].max()

60000

In [22]:
#What is the average transaction amount?
df2["Amount"].mean()

np.float64(17437.5)

In [29]:
#Which user do most of the transactions?
df2["Account name"].value_counts()

Account name
Sandeep          6
Sumit            6
Aman             2
Sandeep Kumar    2
Name: count, dtype: int64